/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_screencaptest_NativeCall */

#ifndef _Included_com_example_screencaptest_NativeCall
#define _Included_com_example_screencaptest_NativeCall
#ifdef __cplusplus
extern "C" {
#endif


JNIEXPORT jint JNICALL Java_com_example_screencaptestapp_NativeCall_getByteFrame
  (JNIEnv *, jobject, jbyteArray jByte);


#ifdef __cplusplus
}
#endif
#endif
